version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  be:
    build: ./news-web-api
    container_name: final_be
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: ${SERVER_PORT} 
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - my_network
  fe:
    image: final_fe
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - be

volumes:
  mysql_data:

networks:
  my_network:
